-- Resources Marketplace seed (run after 007 + 008)
--   supabase db query --file supabase/seed-resources.sql --linked

insert into public.resource_categories (name, slug, description, icon, featured, display_order)
values
  ('UI Kits', 'ui-kits', 'Interfaces and design systems', '◫', true, 0),
  ('Templates', 'templates', 'Layouts ready to ship', '▣', true, 1),
  ('Brand Assets', 'brand', 'Identity and visual language', '◎', false, 2),
  ('Motion Packs', 'motion', 'Loops, transitions, and reels', '▶', true, 3),
  ('Mockups', 'mockups', 'Devices and presentation scenes', '▦', false, 4),
  ('Guides', 'guides', 'Playbooks and frameworks', '≡', false, 5),
  ('Production Systems', 'production', 'Workflows that scale', '⚙', false, 6),
  ('Design Resources', 'design', 'Textures, type, and utilities', '✦', false, 7),
  ('Code Components', 'code', 'React and front-end blocks', '</>', false, 8),
  ('Business Documents', 'business', 'Proposals and client kits', '▤', false, 9)
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  icon = excluded.icon,
  featured = excluded.featured,
  display_order = excluded.display_order;

insert into public.resources (
  slug,
  title,
  short_description,
  full_description,
  thumbnail_url,
  preview_images,
  category_id,
  pricing_type,
  price,
  compare_at_price,
  currency,
  featured,
  status,
  file_formats,
  compatibility,
  license_type,
  tags,
  download_count,
  view_count,
  rating_average,
  rating_count,
  seo_title,
  seo_description,
  published_at
)
select
  v.slug,
  v.title,
  v.short_description,
  v.full_description,
  v.thumbnail_url,
  v.preview_images,
  c.id,
  v.pricing_type::public.pricing_type,
  v.price,
  v.compare_at_price,
  v.currency,
  v.featured,
  'published'::public.resource_status,
  v.file_formats,
  v.compatibility,
  v.license_type,
  v.tags,
  v.download_count,
  v.view_count,
  v.rating_average,
  v.rating_count,
  v.seo_title,
  v.seo_description,
  now()
from (values
  (
    'cinematic-ui-kit',
    'Cinematic UI Kit',
    'Editorial interfaces with motion-ready components.',
    'Production-grade UI kit for creative studios and SaaS brands.',
    '/images/Prj04/cover.jpg',
    array['/images/Prj04/cover.jpg', '/images/Prj06/Cover.jpg'],
    'ui-kits',
    'paid',
    49.00,
    59.00,
    'USD',
    true,
    array['Figma', 'PDF'],
    array['Figma 116+'],
    'commercial',
    array['Figma', 'Web', 'SaaS'],
    2840,
    9200,
    4.90,
    128,
    'Cinematic UI Kit — Premium Figma',
    '120+ components, dark/light modes, documentation.'
  ),
  (
    'portfolio-template-system',
    'Portfolio Template System',
    'Modular case-study templates for designers.',
    'Ship portfolio updates in hours with narrative scroll sections.',
    '/images/Prj12/cover.jpg',
    array['/images/Prj12/cover.jpg'],
    'templates',
    'free',
    0,
    null,
    'USD',
    true,
    array['Figma', 'PNG'],
    array['Figma', 'Framer'],
    'free-commercial',
    array['Free', 'Portfolio'],
    9120,
    18400,
    4.80,
    256,
    'Free Portfolio Template System',
    'Eight page templates with CMS notes.'
  ),
  (
    'device-mockup-studio',
    'Device Mockup Studio',
    'High-resolution device frames with natural lighting.',
    'Present UI and photography in context with smart objects.',
    '/images/Prj08/cover.jpg',
    array['/images/Prj08/cover.jpg'],
    'mockups',
    'free',
    0,
    null,
    'USD',
    false,
    array['PSD'],
    array['Photoshop 2020+'],
    'free-commercial',
    array['Free', 'Mockups'],
    6740,
    11200,
    4.60,
    89,
    'Free Device Mockup Studio',
    'Twelve scenes with shadow controls.'
  ),
  (
    'reel-transition-pack',
    'Reel Transition Pack',
    'Twenty seamless transitions for short-form edits.',
    'Motion presets for Premiere Pro and DaVinci Resolve.',
    '/images/Prj13/cover.jpg',
    array['/images/Prj13/cover.jpg'],
    'motion',
    'paid',
    29.00,
    null,
    'USD',
    false,
    array['MOGRT', 'MP4'],
    array['Premiere Pro 2022+'],
    'commercial',
    array['Premiere', 'Social'],
    3210,
    7600,
    4.90,
    74,
    'Reel Transition Pack',
    '4K-ready transitions with tutorial.'
  )
) as v(
  slug, title, short_description, full_description, thumbnail_url, preview_images,
  category_slug, pricing_type, price, compare_at_price, currency, featured,
  file_formats, compatibility, license_type, tags,
  download_count, view_count, rating_average, rating_count, seo_title, seo_description
)
join public.resource_categories c on c.slug = v.category_slug
on conflict (slug) do update set
  title = excluded.title,
  short_description = excluded.short_description,
  full_description = excluded.full_description,
  thumbnail_url = excluded.thumbnail_url,
  preview_images = excluded.preview_images,
  category_id = excluded.category_id,
  pricing_type = excluded.pricing_type,
  price = excluded.price,
  featured = excluded.featured,
  status = excluded.status,
  tags = excluded.tags,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description;

-- File metadata (upload binaries separately to resource-files/{resource_id}/1/…)
insert into public.resource_files (resource_id, file_name, file_path, file_type, is_primary, version)
select
  r.id,
  v.file_name,
  r.id::text || '/1/' || v.file_name,
  v.file_type,
  true,
  1
from (values
  ('cinematic-ui-kit', 'cinematic-ui-kit.zip', 'application/zip'),
  ('portfolio-template-system', 'portfolio-templates.zip', 'application/zip'),
  ('device-mockup-studio', 'mockup-studio.zip', 'application/zip'),
  ('reel-transition-pack', 'reel-transitions.zip', 'application/zip')
) as v(slug, file_name, file_type)
join public.resources r on r.slug = v.slug
on conflict (storage_bucket, file_path) do nothing;
