#!/usr/bin/env node
/**
 * Scan public/images and regenerate supabase/seed.sql so every file is linked in the DB.
 * Run: node scripts/generate-seed.mjs
 */

import { readdirSync, writeFileSync } from 'fs';
import { dirname, join } from 'path';
import { fileURLToPath } from 'url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const IMAGES = join(ROOT, 'public/images');
const OUT = join(ROOT, 'supabase/seed.sql');

const VIDEO_EXT = new Set(['.mp4', '.mov', '.webm', '.avi', '.m4v', '.MP4', '.MOV']);

/** @type {Array<{ id: string, folder: string, title: string, subtitle: string, tagLeft: string, tagRight: string, coverAlt: string, sortOrder: number }>} */
const PROJECTS = [
  { id: 'prj01', folder: 'Prj01', title: 'Christa Valley International', subtitle: 'Identity · Branding · Design', tagLeft: 'Digital', tagRight: 'Brand System', coverAlt: 'Christa Valley International', sortOrder: 0 },
  { id: 'prj02', folder: 'Prj02', title: 'Glory Theatre Productions', subtitle: 'Identity · Branding · Design', tagLeft: 'Digital', tagRight: 'Brand System', coverAlt: 'Glory Theatre Productions', sortOrder: 1 },
  { id: 'prj03', folder: 'Prj03', title: 'Book Cover Design', subtitle: 'Editorial · Publication · Design', tagLeft: 'Print', tagRight: 'Cover Design', coverAlt: 'Book Cover Design', sortOrder: 2 },
  { id: 'prj04', folder: 'Prj04', title: 'Trek Brand', subtitle: 'Identity · Design · Social Media', tagLeft: 'Digital', tagRight: 'Brand System', coverAlt: 'Trek Brand', sortOrder: 3 },
  { id: 'prj05', folder: 'Prj05', title: 'Glorious Voices', subtitle: 'Identity · Design · Social Media', tagLeft: 'Digital', tagRight: 'Brand System', coverAlt: 'Glorious Voices', sortOrder: 4 },
  { id: 'prj06', folder: 'Prj06', title: '3D Renderings', subtitle: 'Blender 3d · Design · Animation', tagLeft: 'Digital', tagRight: 'Modeling', coverAlt: '3D Renderings', sortOrder: 5 },
  { id: 'prj07', folder: 'Prj07', title: "Revv'd Up", subtitle: 'Identity · Design · Social Media', tagLeft: 'Digital', tagRight: 'Brand System', coverAlt: 'Revvd Up', sortOrder: 6 },
  { id: 'prj08', folder: 'Prj08', title: 'PSS Urbania - Company Profile Photography', subtitle: 'Photography · Editorial · Corporate', tagLeft: 'Digital', tagRight: 'Brand System', coverAlt: 'PSS Urbania - Company Profile Photography', sortOrder: 7 },
  { id: 'prj09', folder: 'Prj09', title: 'Mo Awudu - Spray Painting Kudus', subtitle: 'Photography · Editorial · Documentary', tagLeft: 'Photography', tagRight: 'Street', coverAlt: 'Mo Awudu - Spray Painting Kudus', sortOrder: 8 },
  { id: 'prj10', folder: 'Prj10', title: 'Borehole Drilling - Pakro Nsawon', subtitle: 'Photography · Editorial · Documentary', tagLeft: 'Photography', tagRight: 'Documentary', coverAlt: 'Borehole Drilling - Pakro Nsawon', sortOrder: 9 },
  { id: 'prj11', folder: 'Prj11', title: 'Poster & Flyer Designs', subtitle: 'Design · Social Media', tagLeft: 'Digital', tagRight: 'Marketing', coverAlt: 'Poster & Flyer Designs', sortOrder: 10 },
  { id: 'prj12', folder: 'Prj12', title: 'Photography Gallery', subtitle: 'Photography · Documentary', tagLeft: 'Photography', tagRight: 'Mixed', coverAlt: 'Photography Gallery', sortOrder: 11 },
  { id: 'prj13', folder: 'Prj13', title: 'Motion and Video Productions', subtitle: 'Cinematography · Video Editing · Directing', tagLeft: 'Video', tagRight: 'Motion', coverAlt: 'Motion and Video Productions', sortOrder: 12 },
  { id: 'prj14', folder: 'Prj14', title: 'Drone Photo & Video', subtitle: 'Photography · Video · Directing', tagLeft: 'Mixed', tagRight: 'Media', coverAlt: 'Drone Photo & Video', sortOrder: 13 },
];

function sqlEscape(value) {
  return String(value).replace(/'/g, "''");
}

function listFiles(dir) {
  return readdirSync(dir, { withFileTypes: true })
    .filter((e) => e.isFile())
    .map((e) => e.name)
    .sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));
}

function ext(name) {
  const i = name.lastIndexOf('.');
  return i >= 0 ? name.slice(i) : '';
}

function isVideo(name) {
  return VIDEO_EXT.has(ext(name));
}

function pickCover(files, folder) {
  const preferred = ['cover.jpg', 'Cover.jpg', 'cover.png', 'Cover.png'];
  for (const name of preferred) {
    if (files.includes(name)) return `/images/${folder}/${name}`;
  }
  const firstImage = files.find((f) => !isVideo(f));
  return firstImage ? `/images/${folder}/${firstImage}` : null;
}

function mediaTypeFor(files) {
  const videos = files.filter(isVideo);
  if (videos.length === files.length) return 'video';
  if (videos.length > 0) return 'mixed';
  return 'image';
}

const lines = [];
lines.push('-- Portfolio seed data (generated by scripts/generate-seed.mjs)');
lines.push('begin;');
lines.push('');
lines.push('-- Clear existing content (dev / re-seed)');
lines.push('delete from public.project_media;');
lines.push('delete from public.projects;');
lines.push('delete from public.testimonials;');
lines.push('delete from public.home_slides;');
lines.push('delete from public.career_timeline_entries;');
lines.push('delete from public.skills;');
lines.push('delete from public.about_bio_paragraphs;');
lines.push('');

lines.push(`insert into public.testimonials (id, quote, author, role, sort_order, is_published) values ('00000000-0000-4000-8000-000000000001', '${sqlEscape('Exceptional attention to detail and creative vision. The project exceeded our expectations and brought our brand to life in ways we never imagined.')}', 'Jane Doe', 'Brand Director', 0, true);`);
lines.push(`insert into public.testimonials (id, quote, author, role, sort_order, is_published) values ('00000000-0000-4000-8000-000000000002', '${sqlEscape('Professional, responsive, and incredibly talented. The final deliverables were not just beautiful but strategically aligned with our goals.')}', 'Michael Smith', 'Creative Lead', 1, true);`);
lines.push(`insert into public.testimonials (id, quote, author, role, sort_order, is_published) values ('00000000-0000-4000-8000-000000000003', '${sqlEscape("Working with this team was a game-changer. Their innovative approach and dedication to quality made all the difference in our campaign's success.")}', 'Alexandra Williams', 'Marketing Head', 2, true);`);
lines.push('');

const sliderDir = join(IMAGES, 'slider');
const sliderFiles = listFiles(sliderDir);
sliderFiles.forEach((name, i) => {
  const src = `/images/slider/${name}`;
  lines.push(
    `insert into public.home_slides (src, alt_text, sort_order, is_published) values ('${sqlEscape(src)}', 'Slide ${i + 1}', ${i}, true);`
  );
});
lines.push('');

const skills = [
  'Photography & Videography',
  'Graphic Design & Illustration',
  'Animation & Motion Graphics',
  'Web Design',
  'Drone Operation',
  'Social Media Management',
  'Lighting & Camera Setup',
];
skills.forEach((label, i) => {
  lines.push(`insert into public.skills (label, sort_order, is_published) values ('${sqlEscape(label)}', ${i}, true);`);
});
lines.push('');

const bios = [
  'Creative and detail-oriented Video and Motion Graphics and graphic designer with 5+ years of experience in video production, graphic design, and event photography.',
  'Proficient in Adobe Creative Suite, Blender 3D, and drone operation. Adept at managing social media platforms, creating compelling visual content, and delivering high-quality projects. Skilled in event video and photography, 3D modeling, and branding design.',
  'Passionate about storytelling through visuals and driving engagement through innovative designs',
];
bios.forEach((body, i) => {
  lines.push(`insert into public.about_bio_paragraphs (body, sort_order, is_published) values ('${sqlEscape(body)}', ${i}, true);`);
});
lines.push('');

const timeline = [
  ['top', '4.7%', '2008 – 2012', 'LABONE SENIOR HIGH SCHOOL', 'WASSCE Certificate'],
  ['bottom', '17.2%', '2011', 'PRECIOUS METAL MARKETING COMPANY (PMMC),', 'Attachment'],
  ['top', '29.7%', '2016 – 2020', 'RADFORD UNIVERSITY COLLEGE', 'BSc Graphic Design'],
  ['bottom', '42.2%', '2018', 'PSYPERTXT/ AKATUAPA LIMITED', 'Intern Illustrator'],
  ['top', '54.7%', '2019', 'PARABLES ANIMATION STUDIOS', 'Intern Illustrator/Animator'],
  ['bottom', '67.2%', '2019 – 2021', 'VOME STUDIOS', 'Videographer, Photographer, and Illustrator'],
  ['top', '79.7%', '2021 – Present', 'FREELANCE DESIGNER AND CONTENT CREATOR', 'Leading creative projects and building meaningful brands'],
  ['bottom', '92.2%', '2024 – 2025', 'THEOVISION INTERNATIONAL', 'Video and Motion Graphics Technician'],
];
timeline.forEach(([position, left, period, title, detail], i) => {
  lines.push(
    `insert into public.career_timeline_entries (position, left_offset, period, title, detail, sort_order, is_published) values ('${position}', '${left}', '${sqlEscape(period)}', '${sqlEscape(title)}', '${sqlEscape(detail)}', ${i}, true);`
  );
});
lines.push('');

for (const project of PROJECTS) {
  const dir = join(IMAGES, project.folder);
  const files = listFiles(dir);
  const coverSrc = pickCover(files, project.folder);
  const mediaType = mediaTypeFor(files);
  const coverNames = new Set(['cover.jpg', 'Cover.jpg', 'cover.png', 'Cover.png']);

  lines.push(
    `insert into public.projects (id, title, subtitle, tag_left, tag_right, cover_src, cover_alt, media_type, sort_order, is_published) values ('${project.id}', '${sqlEscape(project.title)}', '${sqlEscape(project.subtitle)}', '${sqlEscape(project.tagLeft)}', '${sqlEscape(project.tagRight)}', '${sqlEscape(coverSrc)}', '${sqlEscape(project.coverAlt)}', '${mediaType}', ${project.sortOrder}, true);`
  );

  let order = 0;
  for (const name of files) {
    if (coverNames.has(name)) continue;
    const src = `/images/${project.folder}/${name}`;
    const itemType = isVideo(name) ? 'video' : 'image';
    lines.push(
      `insert into public.project_media (project_id, src, item_type, sort_order) values ('${project.id}', '${sqlEscape(src)}', '${itemType}', ${order});`
    );
    order += 1;
  }
  lines.push('');
}

lines.push('commit;');
lines.push('');

writeFileSync(OUT, lines.join('\n'));
console.log(`Wrote ${OUT} (${lines.length} lines)`);
