#!/usr/bin/env bash
# Link a Supabase project, apply schema, seed data, and write .env.local
# Usage: ./scripts/setup-supabase.sh <project-ref>
# Example: ./scripts/setup-supabase.sh abcdefghijklmnop

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

PROJECT_REF="${1:-}"
if [[ -z "$PROJECT_REF" ]]; then
  echo "Usage: $0 <project-ref>"
  echo "Find project ref in Supabase Dashboard → Project Settings → General → Reference ID"
  exit 1
fi

if ! command -v supabase >/dev/null 2>&1; then
  echo "Install Supabase CLI: https://supabase.com/docs/guides/cli"
  exit 1
fi

echo "→ Linking project $PROJECT_REF ..."
supabase link --project-ref "$PROJECT_REF"

echo "→ Applying migrations ..."
supabase db push

echo "→ Seeding portfolio content ..."
supabase db query --file supabase/seed.sql --linked

echo "→ Fetching API keys ..."
KEYS_JSON="$(supabase projects api-keys --project-ref "$PROJECT_REF" -o json)"
ANON_KEY="$(echo "$KEYS_JSON" | python3 -c "
import json, sys
keys = json.load(sys.stdin)
for k in keys:
    if k.get('id') == 'anon' or k.get('name') == 'anon':
        print(k['api_key'])
        break
else:
    for k in keys:
        if k.get('type') == 'publishable':
            print(k['api_key'])
            break
")"

if [[ -z "$ANON_KEY" ]]; then
  echo "Could not find anon key. Add VITE_SUPABASE_ANON_KEY manually from Dashboard → API."
  exit 1
fi

SUPABASE_URL="https://${PROJECT_REF}.supabase.co"
ENV_FILE="$ROOT/.env.local"

cat > "$ENV_FILE" <<EOF
# Generated by scripts/setup-supabase.sh — do not commit
VITE_SUPABASE_URL=$SUPABASE_URL
VITE_SUPABASE_ANON_KEY=$ANON_KEY
EOF

echo ""
echo "Done. Wrote $ENV_FILE"
echo "  URL: $SUPABASE_URL"
echo ""
echo "Next: npm run dev"
echo "Also add the same variables in Vercel → Settings → Environment Variables."
